### ISSUE TITLE
README Typos?

### ISSUE THREAD

**Issue by kingthorin** [DevSlop/pixi-crs#6]
https://github.com/DevSlop/pixi-crs/tree/test-pixi-vulnerabilities#test-nr-11-inject-on-the-admin-page-to-find-all-users talks about all users but then has the same link/desc as https://github.com/DevSlop/pixi-crs/tree/test-pixi-vulnerabilities#test-nr-12-inject-on-the-admin-page-to-find-all-likes

Both use:
`.navigateTo('http://172.17.0.2:8001/ADMIN/likes?search[$ne]=1')`

I believe the first should use:
`.navigateTo('http://172.17.0.2:8001/ADMIN/users?search[$ne]=1')`

Actually I think perhaps the links are wrong altogether. Shouldn't they be more of the form: `admin/users/search?search[$ne]=1` ?

**Comment by franbuehler** [comment]
Thank you @kingthorin for this issue and the referenced PR. I have not seen it so far. But these Mongo DB injections were exactly what I was looking for. I will look into it.
Thank you very much for your contribution!

**Comment by kingthorin** [comment]
It seems pixi has been abandon, per it's main README:

> This module is no longer supported. However, it's wildy vulnerable, so if you want to scan it with a scanner, it will light up like a beautiful Christmas tree. :-D

Closing this issue/ticket.
